using System;
using System.Collections.Generic;
using System.Linq;

namespace Solutions
{
    public class Problem2
    {
        /*
             Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
             By starting with 1 and 2, the first 10 terms will be:
               
               1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
               
             By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
             find the sum of the even-valued terms.
        */


        public static void Solution()
        {
            var fibonacci = new List<int> { 1, 2 };
            for (int i = 2; i < 1000; i++)
            {
                if (fibonacci.Last() > 4000000)
                    break;

                fibonacci.Add(fibonacci[i - 1] + fibonacci[i - 2]);
            }


            var evens = new List<int>();
            foreach (var number in fibonacci)
            {
                if (number % 2 == 0)
                    evens.Add(number);
            }


            Console.WriteLine(evens.Sum().ToString("##,###"));
        }
    }
}
